### ISSUE TITLE
Should not show error stack in build ouput when Streams errors are reported

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/vscode-ide#110]
Example for a failed build:

What we _currently_ show:

```
[2020-06-24T14:16:30-04:00][INFO]
ChannelRouter.spl:20:61: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: stateVariable1.
CDISP0092E ERROR: Because of previous compilation errors, the compile process cannot continue.
make: *** [main] Error 1
[2020-06-24T14:16:30-04:00][ERROR]
Error: Failed to build the application ChannelRouter using the Streams instance clean. CDISB5052E The 2 build received an error during build processing. Error code is: '2'.
    at /Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:52099
    at c (/Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:85118)
    at Generator._invoke (/Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:84871)
    at Generator.forEach.e.<computed> [as next] (/Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:85475)
    at n (/Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:131261)
    at s (/Users/nicholls/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:131472)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

What we _should_ show:

```
[2020-06-24T14:16:30-04:00][INFO]
ChannelRouter.spl:20:61: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: stateVariable1.
CDISP0092E ERROR: Because of previous compilation errors, the compile process cannot continue.
make: *** [main] Error 1
[2020-06-24T14:16:30-04:00][ERROR]
Error: Failed to build the application ChannelRouter using the Streams instance clean. CDISB5052E The 2 build received an error during build processing. Error code is: '2'.
```

**Comment by queeniema** [comment]
<img width="980" alt="Screen Shot 2020-06-25 at 11 06 46 AM" src="https://user-images.githubusercontent.com/2454818/85782273-52b66680-b6db-11ea-8b45-10e79c9ddfc2.png">
