### ISSUE TITLE
Unable to add instance - SSL issue

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/vscode-ide#145]
Unable to add new instance into VSCode

2021-04-07T10:56:42.540+02:00][TRACE] Adding Streams instance with payload: {"instanceType":"v5_cpd","existingConnectionId":null}
[2021-04-07T10:56:42.540+02:00][TRACE] ***** Action dispatched: {"type":"instances/setIsAuthenticating","payload":{"connectionId":"streamsInstance_1617785802538","isAuthenticating":true}}
Previous state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”*******”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"}}]
Next state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"},"isAuthenticating":true}]
[2021-04-07T10:56:42.540+02:00][TRACE] Adding Cloud Pak for Data instance with payload: {"connectionId":"streamsInstance_1617785802538","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud"}
[2021-04-07T10:56:42.541+02:00][TRACE] ***** Action dispatched: {"type":"instances/setAuthentication","payload":{"connectionId":"streamsInstance_1617785802538","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”**********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"}}}
Previous state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”*********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"},"isAuthenticating":true}]
Next state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”*********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"},"isAuthenticating":true}]
[2021-04-07T10:56:42.541+02:00][TRACE] Getting Cloud Pak for Data bearer token with payload: {"connectionId":"streamsInstance_1617785802538","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud"}
[2021-04-07T10:56:42.789+02:00][TRACE] ##### REST request: {"method":"post","url":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad00ee105a1e16a79-0000.par01.containers.appdomain.cloud/icp4d-api/v1/authorize","data":"{\"username\":\"jchailloux\",\"password\”:\”*********\”}”}
[2021-04-07T10:56:42.790+02:00][TRACE] ***** Action dispatched: {"type":"instances/setIsAuthenticating","payload":{"connectionId":"streamsInstance_1617785802538","isAuthenticating":false}}
Previous state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”**********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"},"isAuthenticating":true}]
Next state: [{"isDefault":true,"connectionId":"streamsInstance_1617785802538","instanceType":"v5_cpd","authentication":{"cpdVersion":"3.0.0","cpdUrl":"https://cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud","useCpdMasterNodeHost":true,"username":"aaaaa","password”:”*********”,”apiKey":"","rememberPassword":true,"rememberApiKey":true,"authType":"password"},"isAuthenticating":false}]
[2021-04-07T10:56:42.790+02:00][TRACE] Removing Streams instance with payload: {"connectionId":"streamsInstance_1617785802538","shouldRemoveCredentials":true}
[2021-04-07T10:56:42.791+02:00][ERROR] An error occurred during Streams authentication.
[2021-04-07T10:56:42.791+02:00][ERROR] Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: cp4d350-cpd-cp4d350.faroks45-46834198c9aed48ad0XXXXXXXXXX.par01-0000.par01.containers.appdomain.cloud. is not in the cert's altnames: DNS:internal-nginx-svc, DNS:*.svc.cluster.local, DNS:api-svc, DNS:*.api, DNS:ibm-nginx-svc, DNS:zen-core-api
    at Object.checkServerIdentity (tls.js:287:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1511:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)

**Comment by jchailloux** [comment]
Solved by adding

"http.proxySupport": "off" in settings.json

**Comment by urvapatel** [comment]
Added this to the docs for users who are having the same problem. thanks
