### ISSUE TITLE
Support of Cloud Pak for Data 2.5

### ISSUE THREAD

**Issue by markheger** [IBMStreams/vscode-ide#62]
Current version does not work with Cloud Pak for Data 2.5

```
Current value:  https://syss161.pok.stglabs.ibm.com:31350/
[2019-12-19T17:19:26+01:00][ERROR]    Invalid URI "/streams-build/instances/sample-streams/nbg//toolkits"
[2019-12-19T17:19:26+01:00][ERROR]    Error occurred during REFRESH_TOOLKITS
[2019-12-19T17:19:26+01:00][ERROR]  
Error: Invalid URI "/streams-build/instances/sample-streams/nbg//toolkits"
	at Request.init (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:273:31)
	at new Request (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:127:8)
	at request (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/index.js:53:10)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/index.js:100:12
	at Observable._subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/out/src/build/v5/util/streams-rest-v5.js:330:9)
	at Observable._trySubscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:44:25)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:30:22)
	at DoOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/tap.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at MapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/map.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at MapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/map.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at MergeMapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at DoOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/tap.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at MapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/map.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at DoOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/tap.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at CatchOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/catchError.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:22:31
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at WithLatestFromSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/withLatestFrom.js:80:34)
	at WithLatestFromSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at FilterSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/filter.js:52:30)
	at FilterSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Notification.observe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Notification.js:22:50)
	at QueueAction.ObserveOnSubscriber.dispatch (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:48:22)
	at QueueAction.AsyncAction._execute (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
	at QueueAction.execute (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/QueueAction.js:38:18)
	at QueueScheduler.AsyncScheduler.flush (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
	at QueueAction.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/QueueAction.js:32:24)
	at QueueScheduler.Scheduler.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Scheduler.js:11:53)
	at QueueScheduler.AsyncScheduler.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:40:46)
	at ObserveOnSubscriber.scheduleMessage (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:53:40)
	at ObserveOnSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:56:14)
	at ObserveOnSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at CatchSubscriber.Subscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:89:26)
	at CatchSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:17:28
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Observable._subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
	at Observable._trySubscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:44:25)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:30:22)
	at MergeMapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:22:31
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Request._callback (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/out/src/build/v5/util/streams-rest-v5.js:341:21)
	at Request.self.callback (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:185:22)
	at Request.emit (events.js:200:13)
	at Request.EventEmitter.emit (domain.js:471:20)
	at Request.<anonymous> (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:200:13)
	at Request.EventEmitter.emit (domain.js:471:20)
	at IncomingMessage.<anonymous> (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:288:20)
	at IncomingMessage.emit (events.js:205:15)
	at IncomingMessage.EventEmitter.emit (domain.js:471:20)
	at endReadableNT (_stream_readable.js:1154:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2019-12-19T17:19:26+01:00][ERROR]    Invalid URI "/streams-build/instances/sample-streams/nbg//builds"
[2019-12-19T17:19:26+01:00][ERROR]    Error occurred during NEW_BUILD
[2019-12-19T17:19:26+01:00][ERROR]  
Error: Invalid URI "/streams-build/instances/sample-streams/nbg//builds"
	at Request.init (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:273:31)
	at new Request (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:127:8)
	at request (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/index.js:53:10)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/index.js:100:12
	at Observable._subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/out/src/build/v5/util/streams-rest-v5.js:330:9)
	at Observable._trySubscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:44:25)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:30:22)
	at MapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/map.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at CatchOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/catchError.js:32:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:22:31
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at WithLatestFromSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/withLatestFrom.js:80:34)
	at WithLatestFromSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at FilterSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/filter.js:52:30)
	at FilterSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Notification.observe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Notification.js:22:50)
	at QueueAction.ObserveOnSubscriber.dispatch (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:48:22)
	at QueueAction.AsyncAction._execute (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
	at QueueAction.execute (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/QueueAction.js:38:18)
	at QueueScheduler.AsyncScheduler.flush (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
	at QueueAction.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/QueueAction.js:32:24)
	at QueueScheduler.Scheduler.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Scheduler.js:11:53)
	at QueueScheduler.AsyncScheduler.schedule (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:40:46)
	at ObserveOnSubscriber.scheduleMessage (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:53:40)
	at ObserveOnSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/observeOn.js:56:14)
	at ObserveOnSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at CatchSubscriber.Subscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:89:26)
	at CatchSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at MergeMapSubscriber.notifyNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
	at InnerSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
	at InnerSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:17:28
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Observable._subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
	at Observable._trySubscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:44:25)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:30:22)
	at MergeMapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:22:31
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Observable._subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
	at Observable._trySubscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:44:25)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:30:22)
	at MergeMapOperator.call (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
	at Observable.subscribe (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Observable.js:25:31)
	at /Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeTo.js:22:31
	at Object.subscribeToResult (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
	at MergeMapSubscriber._innerSub (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
	at MergeMapSubscriber._tryNext (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
	at MergeMapSubscriber._next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
	at MergeMapSubscriber.Subscriber.next (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/rxjs/internal/Subscriber.js:66:18)
	at Request._callback (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/out/src/build/v5/util/streams-rest-v5.js:341:21)
	at Request.self.callback (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:185:22)
	at Request.emit (events.js:200:13)
	at Request.EventEmitter.emit (domain.js:471:20)
	at Request.<anonymous> (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:200:13)
	at Request.EventEmitter.emit (domain.js:471:20)
	at IncomingMessage.<anonymous> (/Users/hegermar/.vscode/extensions/ibm.ibm-streams-0.5.0/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:288:20)
	at IncomingMessage.emit (events.js:205:15)
	at IncomingMessage.EventEmitter.emit (domain.js:471:20)
	at endReadableNT (_stream_readable.js:1154:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by queeniema** [comment]
@markheger We are currently working on updating the extension to support CPD V2.5.

**Comment by markheger** [comment]
Is there any update available?

**Comment by queeniema** [comment]
@markheger We plan to put out an updated version that supports CPD V2.5 and V3.0 in early April.

**Comment by markheger** [comment]
Connection to CPD verified with VsCode IBM Streams 1.0.1
