### ISSUE TITLE
Local toolkit not found

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/vscode-ide#99]
I have a spl application that requires a specific (newer) toolkit version.
The info.xml file requires com.ibm.streamsx.sttgateway 2.2.1

    <info:toolkit>
      <common:name>com.ibm.streamsx.sttgateway</common:name>
      <common:version>[2.2.1,3.0.0)</common:version>
    </info:toolkit>

The tookits on build server has com.ibm.streamsx.sttgateway 2.1.1
I add the local toolkit path to the newer toolkit version an refresh the toolkits.
The configuration is now:

[2020-06-10T09:24:58+02:00][DEBUG]    The IBM Streams SPL Language Server is starting.
[2020-06-10T09:25:04+02:00][DEBUG]    The IBM Streams SPL Language Server is running.
[2020-06-10T09:26:16+02:00][INFO]   
Streams toolkits:

Build service toolkits:
  com.ibm.streams.cep - 2.1.2
  com.ibm.streams.cybersecurity - 2.1.2
  com.ibm.streams.geospatial - 3.4.2
  com.ibm.streams.pmml - 3.0.1
  com.ibm.streams.rproject - 2.1.3
  com.ibm.streams.rules - 2.1.3
  com.ibm.streams.rulescompiler - 1.2.19
  com.ibm.streams.teda - 2.3.1
  com.ibm.streams.text - 2.3.3
  com.ibm.streams.timeseries - 5.0.3
  com.ibm.streamsx.avro - 1.4.2
  com.ibm.streamsx.datetime - 1.2.1
  com.ibm.streamsx.dps - 4.1.1
  com.ibm.streamsx.elasticsearch - 2.1.5
  com.ibm.streamsx.eventstore - 2.3.3
  com.ibm.streamsx.hbase - 3.8.3
  com.ibm.streamsx.hdfs - 5.2.1
  com.ibm.streamsx.inet - 3.1.2
  com.ibm.streamsx.inetserver - 4.3.2
  com.ibm.streamsx.iot - 1.2.0
  com.ibm.streamsx.jdbc - 1.7.2
  com.ibm.streamsx.jms - 2.0.1
  com.ibm.streamsx.json - 1.5.3
  com.ibm.streamsx.kafka - 3.0.4
  com.ibm.streamsx.mail - 2.0.1
  com.ibm.streamsx.messagehub - 3.0.2
  com.ibm.streamsx.messaging - 5.4.2
  com.ibm.streamsx.mqtt - 1.0.4
  com.ibm.streamsx.network - 3.3.1
  com.ibm.streamsx.objectstorage - 2.1.3
  com.ibm.streamsx.rabbitmq - 1.2.2
  com.ibm.streamsx.sparkmllib - 1.3.1
  com.ibm.streamsx.sttgateway - 2.1.1
  com.ibm.streamsx.topology - 1.14.13
  spl - 1.4.0

Local toolkits from /home/joergboe/git/streamsx.sttgateway/com.ibm.streamsx.sttgateway:
  com.ibm.streamsx.sttgateway - 2.2.1
[2020-06-10T09:26:58+02:00][INFO]     Initializing toolkit index cache...
[2020-06-10T09:27:18+02:00][SUCCESS]  Toolkit indexes cached successfully.

But when I try to compile the application **only the older** build-server version is found:

[2020-06-10T09:28:27+02:00][INFO]     Received request to build.
[2020-06-10T09:28:27+02:00][INFO]     Selected: /home/joergboe/wscode3/application/STTDemoAppVsCode.spl
[2020-06-10T09:28:27+02:00][INFO]     Selected Streams instance: streams.
[2020-06-10T09:28:28+02:00][INFO]     Building the application archive for the application application::STTDemoAppVsCode...
[2020-06-10T09:28:34+02:00][INFO]     Building the application application::STTDemoAppVsCode using the Streams instance streams...
[2020-06-10T09:28:38+02:00][INFO]     
sc -M application::STTDemoAppVsCode -t $STREAMS_INSTALL/toolkits
[2020-06-10T09:28:58+02:00][INFO]     
CDISP0384E ERROR: The STTDemoAppVsCode toolkit requires version [2.2.1,3.0.0) of the com.ibm.streamsx.sttgateway toolkit, but version 2.1.1 of the required toolkit is currently installed.
CDISP0884W WARNING: Errors occurred while the toolkits were loading.

CDISP0092E ERROR: Because of previous compilation errors, the compile process cannot continue.
make: *** [main] Error 1
[2020-06-10T09:28:58+02:00][ERROR]  
Error: Failed to build the application application::STTDemoAppVsCode using the Streams instance streams. CDISB5052E The 25 build received an error during build processing. Error code is: '2'.
	at /home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:52099
	at c (/home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:85118)
	at Generator._invoke (/home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:84871)
	at Generator.forEach.e.<computed> [as next] (/home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:8:85475)
	at n (/home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:131261)
	at s (/home/joergboe/.vscode/extensions/ibm.ibm-streams-1.0.1/dist/extension.js:1:131472)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by markheger** [comment]
Verified the same issue with another toolkit.
It seems that (product) toolkits that are already present on the build service are not added from the local toolkit location into the archive that is uploaded to the build service.

**Comment by joergboe** [comment]
in v1.0.1 I get a new error like:
[2020-06-19T12:07:04+02:00][INFO]     Received request to build.
[2020-06-19T12:07:04+02:00][INFO]     Selected: /home/joergboe/wscode3/application/STTDemoAppVsCode.spl
[2020-06-19T12:07:04+02:00][INFO]     Selected Streams instance: streams.
[2020-06-19T12:07:06+02:00][INFO]     Building the application archive for the application application::STTDemoAppVsCode...
[2020-06-19T12:07:07+02:00][INFO]   
Including the following local toolkits in the application archive:
/home/joergboe/git/streamsx.sttgateway/com.ibm.streamsx.sttgateway - 2.2.2
[2020-06-19T12:07:28+02:00][INFO]     Uploading the application archive...
[2020-06-19T12:08:19+02:00][INFO]     Building the application application::STTDemoAppVsCode using the Streams instance streams...
[2020-06-19T12:08:29+02:00][ERROR]    Failed to build the application application::STTDemoAppVsCode using the Streams instance streams.
[2020-06-19T12:08:29+02:00][ERROR]    CDISA5089E An unexpected error occurred. The error message is '/tmp/build/build.out (No such file or directory)'.
[2020-06-19T12:08:29+02:00][ERROR]  
{
  "method": "get",
  "url": "https://zen-cpd-zen.apps.cp4dstreams-lb-1.fyre.ibm.com/streams-build/instances/streams/zen/85/logmessages",
  "status": 500
}

**Comment by queeniema** [comment]
@joergboe Thanks, will look into this.
